account/urls.py
"""
    Used to manage all the URL's related to User Account
"""
from django.urls import path

from account.views import activate, UserRegisterView, LoginView, LogoutView

app_name = "account"

urlpatterns = [
    path("", UserRegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), {'redirect_if_logged_in': '/product_view'}, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    # path("home/", HomeView.as_view(), name="home"),
    path(
        "activate/^(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/",
        activate,
        name="activate",
    ),
]

product/urls.py
from django.urls import path
from .views import CategoryList, CategoryCreate, CategoryUpdate, CategoryDelete, \
    ProductList, ProductCreate, ProductUpdate, ProductDelete

app_name = 'product'

urlpatterns = [
    path('category_view', CategoryList.as_view(), name="CategoryList"),
    path('category_create', CategoryCreate.as_view(), name="CategoryCreate"),
    path('category_update/<int:pk>', CategoryUpdate.as_view(), name="CategoryUpdate"),
    path('category_delete/<int:pk>', CategoryDelete.as_view(), name="CategoryDelete"),
    path('product_view', ProductList.as_view(), name="ProductList"),
    path('product_create', ProductCreate.as_view(), name="ProductCreate"),
    path('product_update/<int:pk>', ProductUpdate.as_view(), name="ProductUpdate"),
    path('product_delete/<int:pk>', ProductDelete.as_view(), name="ProductDelete"),
]

product_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls")),
    path('', include("product.urls")),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Home{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.js"></script> -->
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap4.min.js"></script>

    <style>

    </style>

    <title>
        {% block page_title %}
        Product Management
        {% endblock %}
    </title>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">

        {% if not request.user.is_authenticated %}
            <div>
                      <h3 style="color: white; font-weight: bold;">Product Management</h3>
            </div>
        {% endif %}

      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if request.user.is_authenticated %}
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                      <a class="nav-link" style="color:white" href="{% url 'product:CategoryList' %}">Category</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link" style="color:white" href="{% url 'product:ProductList' %}">Product</a>
                    </li>

                    <li>
                      <h3 style="color: white; font-weight: bold; margin-left: 340px; text-decoration: underline;">Product Management</h3>
                    </li>
                  </ul>

                  <form class="form-inline my-2 my-lg-0">
                        {% if request.user.is_authenticated %}
                            <button class="nav-link btn btn-secondary" disabled> Logged-in User: {{request.user}}</button>
                        {% endif %}
                      <a class="nav-link btn btn-danger ml-1" style="color:white" href="{% url 'account:logout' %}">Logout</a>
                  </form>
            {% endif %}
        </div>
    </nav>



    {% block content %}
    <!--Messages-->
<!--    {% if messages %}-->
<!--    {% for message in messages %}-->
<!--    <div class="alert alert-dismissible alert-{{message.tags}}">-->
<!--        <button type="button" class="close" data-dismiss="alert">×</button>-->
<!--        <strong>{{message}}</strong>-->
<!--    </div>-->
<!--    {% endfor %}-->
<!--    {% endif %}-->
    <!--End message-->
    {% endblock %}

    {% block body %}{% endblock %}
    {% block script %}{% endblock %}
</body>
</html>

templates/create_view.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}

{% block body %}
<div class="container">
    <h2 class="mt-3">{{header}}:</h2>
    {% include "message.html" %}
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="form-group col-6">
          {% for field in form %}
            <br>
            {{ field.label_tag }}
            {% if field.field.required %} <span class="required_sign">*</span> {% endif %}
            {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
            <p class="help mt-1">{{ field.help_text|safe }}</p>
            {% endif %}
          {% endfor %}
        </div>
      </div>
      <center><button type="submit" class="btn btn-primary mt-2 mb-5">Create</button></center>
    </form>
</div>
{% endblock %}

templates/delete_view.html
{% extends "base.html" %}
{% block title %}Category Delete Page{% endblock %}

{% block body %}
<div class="container">
    <h2 class="mt-3">{{header}}:</h2>
    {% include "message.html" %}
    <form method="post">
        {% csrf_token %}
     
       <h5>Are you sure you want to delete "{{ object }}"?</h5>
        <input type="submit" class="btn btn-danger mt-2" value="Confirm">
        <input type=button class="btn btn-primary mt-2" value="Cancel" onClick="javascript:history.go(-1);">
    </form>
</div>    
{% endblock %}

templates/list_view.html
{% extends "base.html" %}
{% block title %}Category Create Page{% endblock %}

{% block body %}
<div class="container">

<h2 class="text-center mt-3">Category List </h2>
<a href="{% url 'product:CategoryCreate' %}" class="btn btn-primary mb-3">Add</a>
  {% include "message.html" %}
  <table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Category Name</th>
            {% if request.user.is_superuser == True %}
            <th>Action</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for value in data %}
        <tr>
            <td>{{ value.category_name }}</td>
            {% if request.user.is_superuser == True %}
            <td>
                <a href="{% url 'product:CategoryUpdate' value.id %}" class="btn btn-primary mr-2">Update</a>
                <a href="{% url 'product:CategoryDelete' value.id %}" class="btn btn-danger ml-2">Delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block script %}
<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>
{% endblock %}

templates/message.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == "error" %}
        <div class="alert alert-dismissible alert-danger m-2" id="msg" role="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% elif message.tags == "warning" %}
        <div class="alert alert-dismissible alert-warning m-2" id="msg" role="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-dismissible alert-success m-2" id="msg" role="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/product_list_view.html
{% extends "base.html" %}
{% block title %}Product List Page{% endblock %}

{% block body %}
<div class="container">
<h2 class="text-center mt-3">Product List </h2>
<a href="{% url 'product:ProductCreate' %}" class="btn btn-primary mb-3">Add</a>
  {% include "message.html" %}
  <table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
                <th>Product Name</th>
                <th>Product Code</th>
                <th>Price</th>
                <th>Category</th>
                <th>Manufacturing Date</th>
                <th>Expiry date</th>
                <th>Owner</th>
                <th>Status</th>
                <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for value in data %}
        <tr>
            <td>{{ value.name }}</td>
            <td>{{ value.product_code }}</td>
            <td>{{ value.price }}</td>
            <td>{{ value.category_id }}</td>
            <td>{{ value.manufacturing_date }}</td>
            <td>{{ value.expiry_date }}</td>
            <td>{{ value.user_id }}</td>
            <td>{{ value.status }}</td>
            {% if request.user == value.user_id %}
            <td>
                <a href="{% url 'product:ProductUpdate' value.id %}" class="btn btn-primary mr-2">Update</a>
                <a href="{% url 'product:ProductDelete' value.id %}" class="btn btn-danger mr-2">Delete</a>
            </td>
            {% else %}
            <td>
                <button type="button" class="btn btn-primary mr-2" disabled>Update</button>
                <button type="button" class="btn btn-danger mr-2" disabled>Delete</button>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block script %}
<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>
{% endblock %}

templates/update_view.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}

{% block body %}
<div class="container">
    <h2 class="mt-3">{{header}}:</h2>
    {% include "message.html" %}
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="form-group col-6">
        {% for field in form %}
          <br>
          {{ field.label_tag }}
          {% if field.field.required %} <span class="required_sign">*</span> {% endif %}
          {{ field }}
          {{ field.errors }}
          {% if field.help_text %}
          <p class="help mt-1">{{ field.help_text|safe }}</p>
          {% endif %}
        {% endfor %}
          </div>
      </div>
      <center><button type="submit" class="btn btn-primary mt-2 mb-5">Update</button></center>
    </form>
</div>    
{% endblock %}